# Generated by Django 2.2.4 on 2019-10-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
