# Generated by Django 2.2.4 on 2019-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20191030_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active2',
            field=models.BooleanField(default=True),
        ),
    ]
