# Generated by Django 2.2.4 on 2019-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_active2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active2',
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
